[build]
  base = "."
  publish = "public"
  command = "hugo build"

[build.environment]
  HUGO_VERSION = "0.147.0"
  HUGO_ENV = "production"
  TZ = "America/Los Angeles"

[[headers]]
  for = "/media/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"